workflows:
  ios-workflow:
    name: iOS Build & Upload to App Store (Flutter)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app-store-credentials3
        - firebase-secrets
      vars:
        CM_APPLE_DEV_TEAM_ID: "6573BLNWHL"
        APP_STORE_CONNECT_TEAM_ID: "6573BLNWHL"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zoomubik.app
    scripts:
      - name: Restore GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Pod Install
        script: |
          cd ios && pod install --repo-update
      - name: Build Flutter
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          xcode-project use-profiles
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist $CM_EXPORT_OPTIONS_PATH \
            -exportPath build/ipa
    artifacts:
      - ios/build/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
