name: Build iOS App

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Build iOS app (project)
        working-directory: ./ios/App
        run: |
          xcodebuild -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -derivedDataPath build \
            DEVELOPMENT_TEAM=6573BLNWHL \
            build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ios-build
          path: ios/App/build/Build/Products/Release-iphoneos/
